# Generated by Django 4.1 on 2023-12-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity", models.CharField(max_length=255)),
                ("aliases", models.TextField(blank=True, null=True)),
                ("date_of_listing", models.DateField(blank=True, null=True)),
                ("type", models.CharField(max_length=50)),
                ("reason_for_listing", models.TextField(blank=True, null=True)),
                ("source", models.CharField(max_length=255)),
                ("location_1", models.TextField(blank=True, null=True)),
                ("location_2", models.TextField(blank=True, null=True)),
                ("location_3", models.TextField(blank=True, null=True)),
                ("location_4", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Entity",
                "verbose_name_plural": "Entities",
                "db_table": "entity",
            },
        ),
        migrations.CreateModel(
            name="Individual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("individual", models.CharField(max_length=255)),
                ("aliases", models.TextField(blank=True, null=True)),
                ("date_of_listing", models.DateField(blank=True, null=True)),
                ("type", models.CharField(max_length=50)),
                ("reason_for_listing", models.TextField(blank=True, null=True)),
                ("source", models.CharField(max_length=255)),
                ("location_1", models.TextField(blank=True, null=True)),
                ("location_2", models.TextField(blank=True, null=True)),
                ("location_3", models.TextField(blank=True, null=True)),
                ("location_4", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Individual",
                "verbose_name_plural": "Individuals",
                "db_table": "individual",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("kypp_decision", models.CharField(max_length=50)),
                ("sanctioned_regime", models.CharField(max_length=3)),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "db_table": "location",
            },
        ),
    ]
