# Generated by Django 4.1 on 2023-12-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="entity",
            field=models.CharField(max_length=500),
        ),
    ]
