# Generated by Django 4.1 on 2023-12-07 04:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Database", "0002_alter_entity_entity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entity",
            old_name="entity",
            new_name="entity_name",
        ),
        migrations.RenameField(
            model_name="individual",
            old_name="individual",
            new_name="individual_name",
        ),
    ]
