# Generated by Django 4.2.8 on 2024-01-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0004_alter_entity_date_of_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='date_of_listing',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='date_of_listing',
            field=models.DateField(blank=True, null=True),
        ),
    ]
