# Generated by Django 4.2.4 on 2024-01-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0005_alter_entity_date_of_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='date_of_listing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='date_of_listing',
            field=models.TextField(blank=True, null=True),
        ),
    ]
